survey/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import TemplateView
from django.conf.urls.defaults import *


from .models import Survey


from .views import answers_list, answers_detail,\
                survey_detail, survey_edit, survey_add,\
                survey_delete, survey_update,\
                question_add, question_update,question_delete,\
                choice_add, choice_update, choice_delete, delete_image

from .views import VisibleSurveyList, EditableSurveyList


urlpatterns = patterns('',

    # url(r'^visible/$', visible_survey_list, name='surveys-visible'),
    url(r'^visible/$', VisibleSurveyList.as_view(), name='surveys-visible'),
    # url(r'^editable/$', EditableSurveyList.as_view(), name='surveys-editable'),

    url(r'^detail/(?P<survey_slug>[-\w]+)/$', survey_detail, name='survey-detail'),

    url(r'^answers/(?P<survey_slug>[-\w]+)/$', answers_list, name='survey-results'),
    url(r'^answers/(?P<survey_slug>[-\w]+)/(?P<key>[a-zA-Z\d]{10,40})/$', answers_detail, name='answers-detail'),

    # url(r'^edit/(?P<survey_slug>[-\w]+)/$', survey_edit,   name='survey-edit'),
    # url(r'^add/$', survey_add,   name='survey-add'),
    # url(r'^update/(?P<survey_slug>[-\w]+)/$', survey_update,   name='survey-update'),
    # url(r'^delete/(?P<survey_slug>[-\w]+)/$', survey_delete, name='survey-delete'),

    # url(r'^question/add/(?P<survey_slug>[-\w]+)/$', question_add,   name='question-add'),
    # url(r'^question/update/(?P<survey_slug>[-\w]+)/(?P<question_id>\d+)/$', question_update,   name='question-update'),
    # url(r'^question/delete/(?P<survey_slug>[-\w]+)/(?P<question_id>\d+)/$', question_delete,   name='question-delete'),

    # url(r'^choice/add/(?P<question_id>\d+)/$', choice_add,   name='choice-add'),
    # url(r'^choice/update/(?P<question_id>\d+)/(?P<choice_id>\d+)/$', choice_update,   name='choice-update'),
    # url(r'^choice/delete/(?P<survey_slug>[-\w]+)/(?P<choice_id>\d+)/$', choice_delete,   name='choice-delete'),

    # url(r'^delete_image/(?P<model_string>[-\w]+)/(?P<object_id>\d+)/$', delete_image, name='delete-image'),
    url(r'^thank-you', TemplateView.as_view(template_name='survey/thankyou.html')),
    url(r'^no-privileges', TemplateView.as_view(template_name='survey/no_privileges.html')),
    url(r'^$', VisibleSurveyList.as_view(), name='surveys'),
    )

survey/models.py
"""Survey Models
"""
import datetime

from django.db import models
from django.core.cache import cache
from django.template.defaultfilters import date as datefilter
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()

QTYPE_CHOICES = (
    ('T', 'Text Input'),
    ('A', 'Text Area'),
    ('S', 'Select One Choice'),
    ('R', 'Radio List'),
    ('RI','Radio Inline List'),
    ('I', 'Radio Image List'),
    ('C', 'Checkbox List')
)

class SurveyManager(models.Manager):
    pass


class Survey(models.Model):

    title   = models.CharField(_('survey title'), max_length=255)
    slug    = models.SlugField(_('slug'), max_length=255, unique=True)
    description= models.TextField(verbose_name=_("description"),
                            help_text=_("This field appears on the public web site and should give an overview to the interviewee"),
                            blank=True)

    ## Add validation on datetimes
    opens   = models.DateTimeField(_('survey starts accepting submissions on'))
    closes  = models.DateTimeField(_('survey stops accepting submissions on'))
    # Define the behavior of the survey
    visible = models.BooleanField(_('survey is visible'))
    public  = models.BooleanField(_('survey results are public'))
    restricted = models.BooleanField(verbose_name=_("restrict the survey to authentified user")
                                     ,blank=True,default=False)
    allows_multiple_interviews = models.BooleanField(verbose_name=_("allows multiple interviews")
                                                     ,blank=True,default=True)
    template_name = models.CharField(_('template name'),max_length=150,
                                     null=True, blank=True,
        help_text=_("This field is used to define a custom template (Example: 'dj_survey/template/my_add_interview_forms.html')."))

    # Control who can edit the survey
    # TODO: Plug this control in the view used to edit the survey
    created_by = models.ForeignKey(User, related_name="created_surveys")
    editable_by = models.ForeignKey(User,related_name="owned_surveys")

    objects = SurveyManager()

    def __unicode__(self):
        return u' - '.join([self.slug, self.title])

    @property
    def _cache_name(self):
        if not self.id:
            id = 'new'
        else:
            id = int(self.id)
        return 'survey_' + repr(id) + '_status'

    @property
    def open(self):
        if not self.visible: return False
        value = cache.get(self._cache_name)
        if value is not None: return value
        now = datetime.datetime.now()
        if self.opens >= now:
            value = False
            duration = (now - self.opens).seconds
        elif self.closes >= now:
            value = True
            duration = (self.opens - now).seconds
        else:
            value = False
            duration = 60*60*24*31
        if duration:
            cache.set(self._cache_name, value, duration)
        return value

    @property
    def closed(self):
        return not self.open

    @property
    def status(self):
        if not self.visible: return _('private')
        if self.open: return _('open')
        if datetime.now() < self.opens:
            return unicode(_('opens ')) + datefilter(self.opens)
        return _('closed')

    @property
    def answer_count(self):
        if hasattr(self, '_answer_count'):
            return self._answer_count
        self._answer_count = sum(q.answer_count for q in self.questions.iterator())
        return self._answer_count

    @property
    def interview_count(self):
        # NOTSURE: Do we realy need this optimisation?
        if hasattr(self, '_interview_count'):
            return self._interview_count
        self._interview_count = len(SurveyAnswer.objects.filter(
            question__survey=self.id).values('interview_uuid').distinct())
        return self._interview_count

    @property
    def session_key_count(self):
        # NOTSURE: Do we realy need this optimisation?
        if hasattr(self, '_session_key_count'):
            return self._submission_count
        self._submission_count = len(SurveyAnswer.objects.filter(
            question__survey=self.id).values('session_key').distinct())
        return self._submission_count

    def has_answers_from(self, session_key):
        if session_key:
            key = session_key.lower()
        else:
            key = None
        return bool(
            SurveyAnswer.objects.filter(session_key__exact=key,
            question__survey__id__exact=self.id).distinct().count())

    @models.permalink
    def get_absolute_url(self):
        return ('survey-detail', (), {'survey_slug': self.slug })

    def save(self):
        res = super(Survey, self).save()
        cache.delete(self._cache_name)
        return res

    def answers_viewable_by(self, user):
        if not self.visible or user.is_anonymous(): return False
        if self.public or user.is_staff: return True
        return user.has_perm('survey.view_answers')


class SurveyQuestion(models.Model):
    survey = models.ForeignKey(Survey, related_name='questions',
                                 verbose_name=_('survey'))
    qtype = models.CharField(_('question type'), max_length=2,
                                choices=QTYPE_CHOICES)
    required = models.BooleanField(_('required'), default=True)
    text     = models.TextField(_('question text'))
    help_text = models.TextField(null=True, blank=True)
    order = models.IntegerField(verbose_name = _("order"),
                                null=True, blank=True)
    # TODO: Add a button or check box to remove the file. There are several
    # recipes floating on internet. I like the one with a custom widget
    image = models.ImageField(verbose_name=_("image"),
                              upload_to= "survey/images/questions" + "/%Y/%m/%d/",
                              null=True, blank= True)
    # Define if the user must select at least 'choice_num_min' number of
    # choices and at most 'choice_num_max'
    choice_num_min = models.IntegerField(_("minimum number of choices"),
                                         null=True, blank=True,)
    choice_num_max = models.IntegerField(_("maximum number of choices"),
                                         null=True, blank=True,)
    # TODO: Modify the forms to respect the style defined by this attr (html,css)

    qstyle = models.TextField(_("HTML Class"),null=True, blank=True)
    ## model validation for requiring choices.

    @property
    def answer_count(self):
        if hasattr(self, '_answer_count'):
            return self._answer_count
        self._answer_count = self.answers.count()
        return self._answer_count


    def __unicode__(self):
        return u' - '.join([self.survey.slug, self.text])

    class Meta:
        verbose_name = "question"
        unique_together = (('survey', 'text'),)
        order_with_respect_to='survey'
        ordering = ('survey', 'order')
        db_table = "survey_question"

    class Admin:
        list_select_related = True
        list_filter = ('survey', 'qtype')
        list_display_links = ('text',)
        list_display = ('survey', 'text', 'qtype', 'required')
        search_fields = ('text',)

    @models.permalink
    def get_update_url(self):
        return ('question-update', (), {'survey_slug': self.survey.slug,'question_id' :self.id  })

    # TODO: add this a fallback to this optimisation with django ORM.
    @property
    def choice_count(self):
        return self.choices.count()

class SurveyChoice(models.Model):
    ## validate question is of proper qtype
    question = models.ForeignKey(SurveyQuestion, related_name='choices',
                                 verbose_name=_('question'))
    text = models.CharField(_('choice text'), max_length=500)
    # TODO: Add a button or check box to remove the file. There are several
    # recipes floating on internet. I like the one with a custom widget
    image = models.ImageField(verbose_name = _("image"),
                              upload_to= "survey/images/questions" + "/%Y/%m/%d/",
                              null=True ,blank= True)

    order = models.IntegerField(verbose_name = _("order"),
                                null=True, blank=True)

    @models.permalink
    def get_update_url(self):
        return ('choice-update', (), {'question_id': self.question.id,'choice_id' :self.id  })

    @property
    def count(self):
        if hasattr(self, '_count'):
            return self._count
        self._count = SurveyAnswer.objects.filter(question=self.question_id,
                                            text=self.text).count()
        return self._count

    def __unicode__(self):
        return self.text

    class Meta:
        verbose_name = "choice"
        unique_together = (('question', 'text'),)
        order_with_respect_to='question'
        ordering = ('question', 'order')
        db_table = "survey_choice"

class SurveyAnswer(models.Model):
    user = models.ForeignKey(User, related_name='answers',
                             verbose_name=_('user'), editable=False,
                             blank=True,null=True)
    question = models.ForeignKey(SurveyQuestion, related_name='answers',
                                 verbose_name=_('question'),
                                 editable=False)
    ## sessions expire, survey results do not, so keep the key.
    session_key = models.CharField(_('session key'), max_length=40)
    text = models.TextField(_('answer text'))
    submission_date = models.DateTimeField(auto_now=True)
    # UUID is used to calculate the number of interviews
    interview_uuid = models.CharField(_("Interview unique identifier"),max_length=36)


    class Meta:
        # unique_together = (('question', 'session_key'),)
        verbose_name = "answer"

survey/templates/survey/answers_list.html
{% extends "survey/base.html" %}
{% load i18n %}
{% block title %}{{ title }} - Results | Marinexplore{% endblock %}
{% if survey.description %}
    {% block metadescription %}
        <meta name="description" content="{{ title }} results. {{ survey.description|striptags }}">
    {% endblock %}
{% endif %}
{% block css_includes %}
<style type="text/css">
.subheading { font-size: 0.8em; color: #666; text-transform: uppercase; margin:0;}
.question { padding: 2em 0 0 0;margin: 2em 0 0 0;border-top:1px solid #999;}
.question pre { margin-left: 2em; }
.question .bar { margin-top: 0.5em; width: 100%;}
.question .barAnswer { width: 100% !important; text-align: left;}
.question .question-results .barColor { background-color: #1394b3; padding: 0px;}
.question .question-results .barPercent { padding-left: 10px;}
</style>
{% endblock %}
{% block survey_content %}
<h5 class="subheading">Results after {{ survey.interview_count }} {% trans "repl" %}{{ survey.interview_count|pluralize:"y,ies" }}</h5>
<h1>{{ title }}</h1>
{% if survey.description %}<p>{{ survey.description|safe|linebreaks }}</p>{% endif %}
{% for question in survey.questions.all %}
<div class="question">
    <strong>{{ question.text }}</strong>
    <em>({{ question.answer_count }} {% if question.choices.count %}{% trans "Vote" %}{% else %}{% trans "Answer" %}{% endif %}{{ question.answer_count|pluralize:"s" }})</em>
    <div id='results{{forloop.counter}}' class='question-results'>
{% if question.choices.count %}
    {% for choice in question.choices.iterator %}
        <table border="0" cellpadding="0" cellspacing="0" class="bar">
            <caption class="barAnswer">{{ choice.text }}{% ifequal question.qtype "I" %}<br/><img src="{{ choice.image.url }}"/>{% endifequal %}</caption>
            <tr>
                <td style="width: {% widthratio choice.count question.answer_count 100 %}%" class="barColor">{% if choice.count %}&nbsp;{% endif %}</td>
                <td class="barPercent"><strong class="barVotes">{{ choice.count }}&nbsp;{% trans "vote" %}{{ choice.count|pluralize:"s" }}</strong>&nbsp;/&nbsp;{% widthratio choice.count question.answer_count 100 %}%</td>
            </tr>
        </table>
    {% endfor %}
{% else %}
    {% for answer in question.answers.all %}
        <div class="answer">
            <span style="text-transform:uppercase;padding-right:10px;color:#666;font-size:0.8em;">{% if view_submissions %}<a href="{% url 'answers-detail' survey_slug=survey.slug key=answer.session_key %}">{% endif %}{% trans "Answer" %} {{ forloop.counter }}{% if view_submissions %}</a>{% endif %} {% trans "of" %} {{ question.answer_count }}</span>
            {{ answer.text }}
        </div>
    {% endfor %}
{% endif %}
    </div>
</div>
{% endfor %}
{% endblock %}

survey/templates/survey/base.html
{% extends "base.html" %}

survey/templates/survey/choice_confirm_delete.html
{% extends "survey/base.html" %}{% load i18n %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

<form method="post" class="focus-input" action="">
    {% trans 'Are you sure you want to delete the following choice ?' %}
    <ul>
        <li>{{choice}}</li>
    </ul>
<div class="submit-row"><input type="submit" value="{% trans 'Delete' %}" class="default" name="__delete" /></div>
</form>
{% endblock %}

survey/templates/survey/editable_survey_list.html
{% extends "survey/base.html" %}
{% load i18n %}
{% load survey %}
{% block survey_content %}

<h1>Surveys</h1>
<ul class="object-tools"><li><a href="{% url 'survey-add' %}" class="addlink">{% trans "Add survey"  %}</a></li></ul>
<fieldset class="module">
<table style="width: 100%">
    <thead><th>{% trans "Survey"%}</th><th>{% trans "Status"%}</th><th>{% trans "Info"%}</th><th>{% trans "Actions"%}</th></thead>
    {% for survey in object_list %}
    <tr class="{% cycle row1,row2 %}">
        <td><a href="{% url 'survey-detail' survey_slug=survey.slug %}">{{ survey.title }}</a>
        </td>
        <td>{{ survey.status }}</td>
        <td>
        {% if user|can_view_answers:survey %}
            {% if survey.interview_count %}
                <a href="{% url 'survey-results' survey_slug=survey.slug %}">{{ survey.interview_count }} {% trans "Submission"%}{{ survey.interview_count|pluralize:"s" }}</a>
            {% else %}
                {% trans "No Submissions."%}
            {% endif %}
        {% endif %}
        {% if request|has_answered:survey %}You have <a href="{% url 'answers-detail' survey_slug=survey.slug key=request.session.session_key %}">{% trans "completed"%}</a> {% trans "this survey."%}{% endif %}
        </td>
        <td><a href="{% url 'survey-edit' survey_slug=survey.slug %}">{% trans "Edit"  %}</a> <a href="{% url 'survey-delete' survey_slug=survey.slug %}">{% trans "Delete"  %}</a> {% trans "Transfer" %} | {% trans "Publish" %}</td>
    </tr>
    {% endfor %}
</table>
</fieldset>
{% endblock %}

survey/templates/survey/image_confirm_delete.html
{% extends "survey/base.html" %}{% load i18n %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

<form method="post" class="focus-input" action="">
    {% trans 'Are you sure you want to delete this image ?' %}
    <img src="{{ object.get_image_url }}"/>

<div class="submit-row"><input type="submit" value="{% trans 'Delete' %}" class="default" name="__delete" /></div>
</form>
{% endblock %}

survey/templates/survey/no_privileges.html
{% extends "survey/base.html" %}
{% load i18n %}
{% block title %}Insufficient Privileges | Marinexplore{% endblock %}
{% block survey_content %}
    <div class="survey-insufficient-privileges">
        <h3 class="message">{% trans "You have insufficient privileges to view this survey." %}</h3>
    </div>
{% endblock %}

survey/templates/survey/question_add.html
{% extends "survey/base.html" %}{% load i18n %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

{% if question.image %}
    <a href="{% url 'delete-image' model_string=model_string object_id=question.id %}">Delete Image</a>
    <img src="{{ question.get_image_url }}" />
{% endif %}
<form enctype="multipart/form-data" method="post" class="focus-input" action="">
    {{form.as_p}}
<div class="submit-row"><input type="submit" value="{% trans 'Submit' %}" class="default" name="__AddQuestion" /></div>
</form>
{% endblock %}

survey/templates/survey/question_confirm_delete.html
{% extends "survey/base.html" %}{% load i18n %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

<form method="post" class="focus-input" action="">
    {% trans 'Are you sure you want to delete the following question ?' %}
    <ul>
        <li>{{question}}</li>
    </ul>
<div class="submit-row"><input type="submit" value="{% trans 'Delete' %}" class="default" name="__delete" /></div>
</form>
{% endblock %}

survey/templates/survey/survey_add.html
{% extends "survey/base.html" %}{% load i18n %}
{% block scripts %}
{{form.media|safe}}
{% endblock %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="/media/css/forms.css" />
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

<form method="post" class="focus-input" action="">
    <table>
    {{form}}
    </table>

<div class="submit-row"><input type="submit" value="{% trans 'Submit' %}" class="default" name="__AddSurvey" /></div>
</form>
{% endblock %}

survey/templates/survey/survey_confirm_delete.html
{% extends "survey/base.html" %}{% load i18n %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ title }}</h1>

<form method="post" class="focus-input" action="">
    {% trans 'Are you sure you want to delete the following survey ?' %}
    <ul>
        <li>{{survey}}</li>
    </ul>
{% for question in survey.forms %}{{ question.as_p }}{% endfor %}
<div class="submit-row"><input type="submit" value="{% trans 'Delete' %}" class="default" name="__delete" /></div>
</form>
{% endblock %}

survey/templates/survey/survey_detail.html
{% extends "survey/base.html" %}
{% load i18n %}
{% block title %}{{ title }} - Survey | Marinexplore{% endblock %}
{% if survey.description %}
    {% block metadescription %}
        <meta name="description" content="{{ survey.description|striptags }}">
    {% endblock %}
{% endif %}
{% block survey_content %}
<h1>{{ title }}</h1>
{% if survey.description %}
    <p>{{ survey.description|safe|linebreaks }}</p>
{% endif %}
<form method="post" class="survey-form" action="">
    <fieldset>
        {% csrf_token %}
        {% for question_form in survey.forms %}
            {{ question_form.as_template }}
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block" data-disable-on-click="1">Submit Survey</button>
    </fieldset>
</form>
{% endblock %}

survey/templates/survey/survey_edit.html
{% extends "survey/base.html" %}
{% load i18n %}
{% load survey %}
{% block styles %}
<style type="text/css">
input[type="radio"] { vertical-align: top; }
</style>
{% endblock %}
{% block survey_content %}
<h1>{{ survey.title }}</h1>
<ul class="object-tools"><li><a href="{% url 'survey-detail' survey_slug=survey.slug %}" class="addlink">{% trans "View Online" %}</a></li></ul>
<table style="width: 100%">
    <thead>
        <th>{% trans "Object type" %}</th><th>{% trans "order" %}</th><th>{% trans "type" %}</th>
        <th>{% trans "Object" %}</th><th>{% trans "Actions" %}</th>
    </thead>
    <tr class="{% cycle row1,row2 %}">
        <td>{% trans "Survey"  %}</td>
        <td>-</td>
        <td>-</td>
        <td>

            <p> {{ survey.description }}</p>
            <p> {{ survey.opens }}</p>
            <p> {{ survey.closes }}</p>
        </td>
        <td>
            <a href="{% url 'survey-update' survey_slug=survey.slug %}">{% trans "Update"  %}</a>
            <a href="{% url 'survey-delete' survey_slug=survey.slug %}">{% trans "Delete"  %}</a>
            <a href="{% url 'question-add' survey_slug=survey.slug %}">{% trans "Add a question"  %}</a>
        </td>
    </tr>
    {% for question in survey.questions.all|order_by:"order" %}
        <tr>
            <td>{% trans "Question"  %}</td>
            <td>{{ question.order }}</td>
            <td>{{ question.get_qtype_display }}</td>
            <td>
                <p>{{ question.text }}</p>
                <p>{{ question.qstyle }}</p>
            </td>
            <td>
                <a href="{% url 'question-update' survey_slug=survey.slug question_id=question.id %}">{% trans "Update"  %}</a>
                <a href="{% url 'question-delete' survey_slug=survey.slug question_id=question.id %}">{% trans "Delete"  %}</a>
                <a href="{% url 'choice-add' question_id=question.id %}">{% trans "Add a choice"  %}</a>
            </td>
        </tr>
        {% for choice in question.choices.all|order_by:"order" %}
            <tr>
                <td>{% trans "choice"  %}</td>
                <td>{{ choice.order }}</td>
                <td>-</td>
                <td>
                    <p>{{ choice.text }}</p>
                </td>
                <td>
                    <a href="{% url 'choice-update' question_id=question.id choice_id=choice.id %}">{% trans "Update"  %}</a>
                    <a href="{% url 'choice-delete' survey_slug=survey.slug choice_id=choice.id %}">{% trans "Delete"  %}</a>
                </td>
            </tr>
        {% endfor %}
    {% endfor %}

</table>

{% endblock %}

survey/templates/survey/survey_list.html
{% extends "survey/base.html" %}
{% load i18n %}
{% load survey %}
{% block title %}Surveys | Marinexplore{% endblock %}
{% block survey_content %}
<table class="table survey-listing">
    <thead>
        <th colspan="2">{% trans "Surveys" %}</th>
    </thead>
    <tbody>
    {% for survey in object_list %}
    {% if survey.open or user|can_view_answers:survey %}
    <tr class="{% cycle row1,row2 %}">
        <td>
            {% if survey.open and not request|has_answered:survey %}
                <a href="{% url 'survey-detail' survey_slug=survey.slug %}">{{ survey.title }}</a>
            {% else %}
                {{ survey.title }}
            {% endif %}
            {% if request|has_answered:survey %}
                <a class="survey-status survey-status-completed" href="{% url 'answers-detail' survey_slug=survey.slug key=request.session.session_key %}">Completed</a>
            {% elif survey.status != 'open' %}
                <span class="survey-status survey-status-{{ survey.status }}">{{ survey.status }}</span>
            {% endif %}
        </td>
        <td class="responses">
        {% if user|can_view_answers:survey %}
            {% if survey.interview_count %}
                <a href="{% url 'survey-results' survey_slug=survey.slug %}">{{ survey.interview_count }} Response{{ survey.interview_count|pluralize }}</a>
            {% else %}
                -
            {% endif %}
        {% else %}
            &nbsp;
        {% endif %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
{% endblock %}

survey/templates/survey/thankyou.html
{% extends "survey/base.html" %}
{% load i18n %}
{% block title %}Survey Completed | Marinexplore{% endblock %}
{% block survey_content %}
    <div class="survey-thank-you">
        <h3 class="message">{% trans "Thank you for your response." %}</h3>
    </div>
{% endblock %}